name: Build Release

on: [push]

jobs:
    release-build:
        name: Release Build
        runs-on: windows-2019

        steps:
            - name: Checkout master
              uses: actions/checkout@v2

            - name: Set python version
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9.x

            - name: Install Pipenv
              run: |
                  pip install pipenv

            - name: Install Python dependencies
              run: |
                  pipenv install

            - name: Build executable
              run: |
                  pipenv run build

            - name: Archive build
              uses: thedoctor0/zip-release@master
              with:
                  filename: 'mimic-win64'
                  directory: 'dist'

    debug-build:
        name: Debug Build
        runs-on: windows-2019

        steps:
            - name: Checkout master
              uses: actions/checkout@v2
