name: Build Release

on: [push]

jobs:
    release-build:
        name: Release Build
        runs-on: windows-2019

        steps:
            - name: Checkout master
              uses: actions/checkout@v2

            - name: Set python version
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9.x

            - name: Install Pipenv
              run: |
                  pip install pipenv

            - name: Install Python dependencies
              run: |
                  pipenv install

            - name: Build executable
              run: |
                  pipenv run build

            - name: Archive build
              run: |
                  7z a -tzip mimic-win64.zip .\dist\mimic\*

            - name: Create pre-release
              uses: softprops/action-gh-release@v1
              with:
                  files: mimic-win64.zip
                  prerelease: yes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    debug-build:
        name: Debug Build
        runs-on: windows-2019

        steps:
            - name: Checkout master
              uses: actions/checkout@v2
